# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e4bea91d13efe0fe9846a4672727b78eed35d3ed4dd396e79d778be54f3bf516b9d9a605fb27ebdc53b8e85881fb35df49bdbd9ddfb0225d6241ea0adadb150

test:
  secret_key_base: 4233eeae88e99b222bb13209ed0fe2e29f15cc29df62476af0c7a1bcf633a785714d8ec01ad45ad8cc1a85f7141c5197cf04fc0163ed624b463e5a0c32a626ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
