# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-18 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.TextField(default=object),
            preserve_default=False,
        ),
    ]
